reduce diff changes

diff --git a/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2 b/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2
--- a/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2
+++ b/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2
@@ -8,10 +8,10 @@ CATALINA_PID=$FISHEYE_HOME/var/catalina.pid
 CATALINA_LOG=$FISHEYE_HOME/var/log/catalina.out
 
 case "`uname`" in
-    Darwin*) if [ -z "$JAVA_HOME" ] ; then
-        JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
-    fi
-    ;;
+  Darwin*) if [ -z "$JAVA_HOME" ] ; then
+             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
+           fi
+           ;;
 esac
 
 if [ -z "$FISHEYE_CATALINA" ]; then
@@ -27,25 +27,25 @@ if [ ! -f "$FISHEYE_CATALINA/fisheyeboot.jar" ] ; then
 fi
 
 if [ -z "$JAVACMD" ] ; then
-    if [ -n "$JAVA_HOME"  ] ; then
-        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-            # IBM's JDK on AIX uses strange locations for the executables
-            JAVACMD="$JAVA_HOME/jre/sh/java"
-        else
-            JAVACMD="$JAVA_HOME/bin/java"
-        fi
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
     else
-        JAVACMD=`which java 2> /dev/null `
-        if [ -z "$JAVACMD" ] ; then
-            JAVACMD=java
-        fi
+      JAVACMD="$JAVA_HOME/bin/java"
     fi
+  else
+    JAVACMD=`which java 2> /dev/null `
+    if [ -z "$JAVACMD" ] ; then
+        JAVACMD=java
+    fi
+  fi
 fi
 
 if [ ! -x "$JAVACMD" ] ; then
-    echo "Error: JAVA_HOME is not defined correctly."
-    echo "  We cannot execute $JAVACMD"
-    exit 1
+  echo "Error: JAVA_HOME is not defined correctly."
+  echo "  We cannot execute $JAVACMD"
+  exit 1
 fi
 
 FISHEYE_OPTS=`$JAVACMD -cp $FISHEYE_CATALINA/fisheyeboot.jar com.cenqua.fisheye.boot.OptsSetter`
