add foreground support

diff --git a/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2 b/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2
--- a/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2
+++ b/templates/opt/atlassian/fisheye/bin/fisheyectl.sh.j2
@@ -5,6 +5,13 @@
 FISHEYE_HOME="{{ fisheye_catalina }}"
 FISHEYE_INST="{{ fisheye_home }}"
 
+PRGRUNMODE=false
+if [ "$2" = "-fg" ] || [ "$2" = "run" ]  ; then
+    PRGRUNMODE=true
+else
+    echo "To run Fisheye in the foreground, start the server with $0 -fg"
+fi
+
 case "`uname`" in
     Darwin*) if [ -z "$JAVA_HOME" ] ; then
         JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
@@ -61,76 +68,83 @@ if [ -z "$CATALINA_PID" ] ; then
 fi
 export CATALINA_PID
 
-if [ "$1" = "start" ] ; then
-    if [ ! -z "$CATALINA_PID" ]; then
-        if [ -f "$CATALINA_PID" ]; then
-            if [ -s "$CATALINA_PID" ]; then
-                echo "Existing PID file found during start."
-                if [ -r "$CATALINA_PID" ]; then
-                    PID=`cat "$CATALINA_PID"`
-                    ps -p $PID >/dev/null 2>&1
-                    if [ $? -eq 0 ] ; then
-                        echo "Tomcat appears to still be running with PID $PID. Start aborted."
-                        exit 1
-                    else
-                        echo "Removing/clearing stale PID file."
-                        rm -f "$CATALINA_PID" >/dev/null 2>&1
-                        if [ $? != 0 ]; then
-                            if [ -w "$CATALINA_PID" ]; then
-                                cat /dev/null > "$CATALINA_PID"
-                            else
-                                echo "Unable to remove or clear stale PID file. Start aborted."
-                                exit 1
+case "$1" in
+    start)
+        if [ ! -z "$CATALINA_PID" ]; then
+            if [ -f "$CATALINA_PID" ]; then
+                if [ -s "$CATALINA_PID" ]; then
+                    echo "Existing PID file found during start."
+                    if [ -r "$CATALINA_PID" ]; then
+                        PID=`cat "$CATALINA_PID"`
+                        ps -p $PID >/dev/null 2>&1
+                        if [ $? -eq 0 ] ; then
+                            echo "Tomcat appears to still be running with PID $PID. Start aborted."
+                            exit 1
+                        else
+                            echo "Removing/clearing stale PID file."
+                            rm -f "$CATALINA_PID" >/dev/null 2>&1
+                            if [ $? != 0 ]; then
+                                if [ -w "$CATALINA_PID" ]; then
+                                    cat /dev/null > "$CATALINA_PID"
+                                else
+                                    echo "Unable to remove or clear stale PID file. Start aborted."
+                                    exit 1
+                                fi
                             fi
                         fi
-                    fi
-                else
-                    echo "Unable to read PID file. Start aborted."
-                    exit 1
-                fi
-            else
-                rm -f "$CATALINA_PID" >/dev/null 2>&1
-                if [ $? != 0 ]; then
-                    if [ ! -w "$CATALINA_PID" ]; then
-                        echo "Unable to remove or write to empty PID file. Start aborted."
+                    else
+                        echo "Unable to read PID file. Start aborted."
                         exit 1
                     fi
+                else
+                    rm -f "$CATALINA_PID" >/dev/null 2>&1
+                    if [ $? != 0 ]; then
+                        if [ ! -w "$CATALINA_PID" ]; then
+                            echo "Unable to remove or write to empty PID file. Start aborted."
+                            exit 1
+                        fi
+                    fi
                 fi
             fi
         fi
-    fi
 
-    cd $FISHEYE_INST
-    mkdir -p $FISHEYE_INST/var/log
-    CMD="$FISHEYE_CMD $@ $FISHEYE_ARGS"
-    echo "Starting FishEye/Crucible... Output redirected to $FISHEYE_INST/var/log/fisheye.out"
-    nohup sh -c "exec $CMD" >> $FISHEYE_INST/var/log/fisheye.out 2>&1 &
+        cd $FISHEYE_INST
+        mkdir -p $FISHEYE_INST/var/log
+        CMD="$FISHEYE_CMD $@ $FISHEYE_ARGS"
+        echo "Starting FishEye/Crucible... Output redirected to $FISHEYE_INST/var/log/fisheye.out"
+        if [ "$PRGRUNMODE" = "true" ] ; then
+            nohup sh -c "exec $CMD" >> $FISHEYE_INST/var/log/fisheye.out 2>&1
+        else
+            nohup sh -c "exec $CMD" >> $FISHEYE_INST/var/log/fisheye.out 2>&1 &
+        fi
 
-    sleep 3
-    echo $! > "$CATALINA_PID"
-elif [ "$1" = "stop" ] ; then
-    if [ ! -z "$CATALINA_PID" ]; then
-        if [ -f "$CATALINA_PID" ]; then
-            if [ -s "$CATALINA_PID" ]; then
-                kill -0 `cat "$CATALINA_PID"` >/dev/null 2>&1
-                if [ $? -gt 0 ]; then
-                    echo "PID file found but no matching process was found. Stop aborted."
-                    exit 1
+        sleep 3
+        echo $! > "$CATALINA_PID"
+        ;;
+    stop)
+        if [ ! -z "$CATALINA_PID" ]; then
+            if [ -f "$CATALINA_PID" ]; then
+                if [ -s "$CATALINA_PID" ]; then
+                    kill -0 `cat "$CATALINA_PID"` >/dev/null 2>&1
+                    if [ $? -gt 0 ]; then
+                        echo "PID file found but no matching process was found. Stop aborted."
+                        exit 1
+                    fi
+                else
+                    echo "PID file is empty and has been ignored."
                 fi
             else
-                echo "PID file is empty and has been ignored."
+                echo "\$CATALINA_PID was set but the specified file does not exist. Is Tomcat running? Stop aborted."
+                exit 1
             fi
-        else
-            echo "\$CATALINA_PID was set but the specified file does not exist. Is Tomcat running? Stop aborted."
-            exit 1
         fi
-    fi
 
-    exec $FISHEYE_CMD $@ $FISHEYE_ARGS
+        exec $FISHEYE_CMD $@ $FISHEYE_ARGS
 
-    sleep 3
-    rm -f "$CATALINA_PID" >/dev/null 2>&1
-else
-    exec $FISHEYE_CMD $@ $FISHEYE_ARGS
-fi
-
+        sleep 3
+        rm -f "$CATALINA_PID" >/dev/null 2>&1
+        ;;
+    *)
+        exec $FISHEYE_CMD $@ $FISHEYE_ARGS
+        ;;
+esac
